### ISSUE TITLE
Jekyll theme not supported by github pages 

### ISSUE THREAD

**Issue by amxra** [yefim/yefeme#2]
Hi, 

I like your yefeme theme for Jekyll and I'm trying to use it for a project but GitHub keeps sending me an error message about how it is not supported by GitHub Pages and it wouldn't work. Can you please help me out

**Comment by yefim** [comment]
Can you try using https://github.com/benbalter/jekyll-remote-theme?

**Comment by amxra** [comment]
this works! thank you so much!
